/* EchoServerH.h
   Generated by gSOAP 2.7.10 from EchoServer.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef EchoServerH_H
#define EchoServerH_H
#include "EchoServerStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__string(struct soap*, std::string const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__string(struct soap*, const std::string *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_xsd__string(struct soap*, std::string *, const char*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_xsd__string(struct soap*, const char*, std::string*, const char*);
SOAP_FMAC5 std::string * SOAP_FMAC6 soap_new_xsd__string(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__string(struct soap*, std::string*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_instantiate_xsd__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);
SOAP_FMAC5 std::string * SOAP_FMAC6 soap_new_std__string(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__string(struct soap*, std::string*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Fault * SOAP_FMAC6 soap_new_SOAP_ENV__Fault(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Reason * SOAP_FMAC6 soap_new_SOAP_ENV__Reason(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Detail * SOAP_FMAC6 soap_new_SOAP_ENV__Detail(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Code * SOAP_FMAC6 soap_new_SOAP_ENV__Code(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Header * SOAP_FMAC6 soap_new_SOAP_ENV__Header(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_EchoServer__EchoWithApplicationData
#define SOAP_TYPE_EchoServer__EchoWithApplicationData (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_EchoServer__EchoWithApplicationData(struct soap*, struct EchoServer__EchoWithApplicationData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_EchoServer__EchoWithApplicationData(struct soap*, const struct EchoServer__EchoWithApplicationData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_EchoServer__EchoWithApplicationData(struct soap*, const struct EchoServer__EchoWithApplicationData *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_EchoServer__EchoWithApplicationData(struct soap*, const char*, int, const struct EchoServer__EchoWithApplicationData *, const char*);
SOAP_FMAC3 struct EchoServer__EchoWithApplicationData * SOAP_FMAC4 soap_get_EchoServer__EchoWithApplicationData(struct soap*, struct EchoServer__EchoWithApplicationData *, const char*, const char*);
SOAP_FMAC3 struct EchoServer__EchoWithApplicationData * SOAP_FMAC4 soap_in_EchoServer__EchoWithApplicationData(struct soap*, const char*, struct EchoServer__EchoWithApplicationData *, const char*);
SOAP_FMAC5 struct EchoServer__EchoWithApplicationData * SOAP_FMAC6 soap_new_EchoServer__EchoWithApplicationData(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_EchoServer__EchoWithApplicationData(struct soap*, struct EchoServer__EchoWithApplicationData*);
SOAP_FMAC3 struct EchoServer__EchoWithApplicationData * SOAP_FMAC4 soap_instantiate_EchoServer__EchoWithApplicationData(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_EchoServer__EchoWithApplicationData(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_EchoServer__EchoWithApplicationDataResponse
#define SOAP_TYPE_EchoServer__EchoWithApplicationDataResponse (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_EchoServer__EchoWithApplicationDataResponse(struct soap*, struct EchoServer__EchoWithApplicationDataResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_EchoServer__EchoWithApplicationDataResponse(struct soap*, const struct EchoServer__EchoWithApplicationDataResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_EchoServer__EchoWithApplicationDataResponse(struct soap*, const struct EchoServer__EchoWithApplicationDataResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_EchoServer__EchoWithApplicationDataResponse(struct soap*, const char*, int, const struct EchoServer__EchoWithApplicationDataResponse *, const char*);
SOAP_FMAC3 struct EchoServer__EchoWithApplicationDataResponse * SOAP_FMAC4 soap_get_EchoServer__EchoWithApplicationDataResponse(struct soap*, struct EchoServer__EchoWithApplicationDataResponse *, const char*, const char*);
SOAP_FMAC3 struct EchoServer__EchoWithApplicationDataResponse * SOAP_FMAC4 soap_in_EchoServer__EchoWithApplicationDataResponse(struct soap*, const char*, struct EchoServer__EchoWithApplicationDataResponse *, const char*);
SOAP_FMAC5 struct EchoServer__EchoWithApplicationDataResponse * SOAP_FMAC6 soap_new_EchoServer__EchoWithApplicationDataResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_EchoServer__EchoWithApplicationDataResponse(struct soap*, struct EchoServer__EchoWithApplicationDataResponse*);
SOAP_FMAC3 struct EchoServer__EchoWithApplicationDataResponse * SOAP_FMAC4 soap_instantiate_EchoServer__EchoWithApplicationDataResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_EchoServer__EchoWithApplicationDataResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_EchoServer__EchoWithSessionData
#define SOAP_TYPE_EchoServer__EchoWithSessionData (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_EchoServer__EchoWithSessionData(struct soap*, struct EchoServer__EchoWithSessionData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_EchoServer__EchoWithSessionData(struct soap*, const struct EchoServer__EchoWithSessionData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_EchoServer__EchoWithSessionData(struct soap*, const struct EchoServer__EchoWithSessionData *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_EchoServer__EchoWithSessionData(struct soap*, const char*, int, const struct EchoServer__EchoWithSessionData *, const char*);
SOAP_FMAC3 struct EchoServer__EchoWithSessionData * SOAP_FMAC4 soap_get_EchoServer__EchoWithSessionData(struct soap*, struct EchoServer__EchoWithSessionData *, const char*, const char*);
SOAP_FMAC3 struct EchoServer__EchoWithSessionData * SOAP_FMAC4 soap_in_EchoServer__EchoWithSessionData(struct soap*, const char*, struct EchoServer__EchoWithSessionData *, const char*);
SOAP_FMAC5 struct EchoServer__EchoWithSessionData * SOAP_FMAC6 soap_new_EchoServer__EchoWithSessionData(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_EchoServer__EchoWithSessionData(struct soap*, struct EchoServer__EchoWithSessionData*);
SOAP_FMAC3 struct EchoServer__EchoWithSessionData * SOAP_FMAC4 soap_instantiate_EchoServer__EchoWithSessionData(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_EchoServer__EchoWithSessionData(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_EchoServer__EchoWithSessionDataResponse
#define SOAP_TYPE_EchoServer__EchoWithSessionDataResponse (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_EchoServer__EchoWithSessionDataResponse(struct soap*, struct EchoServer__EchoWithSessionDataResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_EchoServer__EchoWithSessionDataResponse(struct soap*, const struct EchoServer__EchoWithSessionDataResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_EchoServer__EchoWithSessionDataResponse(struct soap*, const struct EchoServer__EchoWithSessionDataResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_EchoServer__EchoWithSessionDataResponse(struct soap*, const char*, int, const struct EchoServer__EchoWithSessionDataResponse *, const char*);
SOAP_FMAC3 struct EchoServer__EchoWithSessionDataResponse * SOAP_FMAC4 soap_get_EchoServer__EchoWithSessionDataResponse(struct soap*, struct EchoServer__EchoWithSessionDataResponse *, const char*, const char*);
SOAP_FMAC3 struct EchoServer__EchoWithSessionDataResponse * SOAP_FMAC4 soap_in_EchoServer__EchoWithSessionDataResponse(struct soap*, const char*, struct EchoServer__EchoWithSessionDataResponse *, const char*);
SOAP_FMAC5 struct EchoServer__EchoWithSessionDataResponse * SOAP_FMAC6 soap_new_EchoServer__EchoWithSessionDataResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_EchoServer__EchoWithSessionDataResponse(struct soap*, struct EchoServer__EchoWithSessionDataResponse*);
SOAP_FMAC3 struct EchoServer__EchoWithSessionDataResponse * SOAP_FMAC4 soap_instantiate_EchoServer__EchoWithSessionDataResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_EchoServer__EchoWithSessionDataResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_EchoServer__Echo
#define SOAP_TYPE_EchoServer__Echo (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_EchoServer__Echo(struct soap*, struct EchoServer__Echo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_EchoServer__Echo(struct soap*, const struct EchoServer__Echo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_EchoServer__Echo(struct soap*, const struct EchoServer__Echo *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_EchoServer__Echo(struct soap*, const char*, int, const struct EchoServer__Echo *, const char*);
SOAP_FMAC3 struct EchoServer__Echo * SOAP_FMAC4 soap_get_EchoServer__Echo(struct soap*, struct EchoServer__Echo *, const char*, const char*);
SOAP_FMAC3 struct EchoServer__Echo * SOAP_FMAC4 soap_in_EchoServer__Echo(struct soap*, const char*, struct EchoServer__Echo *, const char*);
SOAP_FMAC5 struct EchoServer__Echo * SOAP_FMAC6 soap_new_EchoServer__Echo(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_EchoServer__Echo(struct soap*, struct EchoServer__Echo*);
SOAP_FMAC3 struct EchoServer__Echo * SOAP_FMAC4 soap_instantiate_EchoServer__Echo(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_EchoServer__Echo(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_EchoServer__EchoResponse
#define SOAP_TYPE_EchoServer__EchoResponse (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_EchoServer__EchoResponse(struct soap*, struct EchoServer__EchoResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_EchoServer__EchoResponse(struct soap*, const struct EchoServer__EchoResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_EchoServer__EchoResponse(struct soap*, const struct EchoServer__EchoResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_EchoServer__EchoResponse(struct soap*, const char*, int, const struct EchoServer__EchoResponse *, const char*);
SOAP_FMAC3 struct EchoServer__EchoResponse * SOAP_FMAC4 soap_get_EchoServer__EchoResponse(struct soap*, struct EchoServer__EchoResponse *, const char*, const char*);
SOAP_FMAC3 struct EchoServer__EchoResponse * SOAP_FMAC4 soap_in_EchoServer__EchoResponse(struct soap*, const char*, struct EchoServer__EchoResponse *, const char*);
SOAP_FMAC5 struct EchoServer__EchoResponse * SOAP_FMAC6 soap_new_EchoServer__EchoResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_EchoServer__EchoResponse(struct soap*, struct EchoServer__EchoResponse*);
SOAP_FMAC3 struct EchoServer__EchoResponse * SOAP_FMAC4 soap_instantiate_EchoServer__EchoResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_EchoServer__EchoResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_EchoServer__ToLower
#define SOAP_TYPE_EchoServer__ToLower (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_EchoServer__ToLower(struct soap*, struct EchoServer__ToLower *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_EchoServer__ToLower(struct soap*, const struct EchoServer__ToLower *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_EchoServer__ToLower(struct soap*, const struct EchoServer__ToLower *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_EchoServer__ToLower(struct soap*, const char*, int, const struct EchoServer__ToLower *, const char*);
SOAP_FMAC3 struct EchoServer__ToLower * SOAP_FMAC4 soap_get_EchoServer__ToLower(struct soap*, struct EchoServer__ToLower *, const char*, const char*);
SOAP_FMAC3 struct EchoServer__ToLower * SOAP_FMAC4 soap_in_EchoServer__ToLower(struct soap*, const char*, struct EchoServer__ToLower *, const char*);
SOAP_FMAC5 struct EchoServer__ToLower * SOAP_FMAC6 soap_new_EchoServer__ToLower(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_EchoServer__ToLower(struct soap*, struct EchoServer__ToLower*);
SOAP_FMAC3 struct EchoServer__ToLower * SOAP_FMAC4 soap_instantiate_EchoServer__ToLower(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_EchoServer__ToLower(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_EchoServer__ToLowerResponse
#define SOAP_TYPE_EchoServer__ToLowerResponse (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_EchoServer__ToLowerResponse(struct soap*, struct EchoServer__ToLowerResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_EchoServer__ToLowerResponse(struct soap*, const struct EchoServer__ToLowerResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_EchoServer__ToLowerResponse(struct soap*, const struct EchoServer__ToLowerResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_EchoServer__ToLowerResponse(struct soap*, const char*, int, const struct EchoServer__ToLowerResponse *, const char*);
SOAP_FMAC3 struct EchoServer__ToLowerResponse * SOAP_FMAC4 soap_get_EchoServer__ToLowerResponse(struct soap*, struct EchoServer__ToLowerResponse *, const char*, const char*);
SOAP_FMAC3 struct EchoServer__ToLowerResponse * SOAP_FMAC4 soap_in_EchoServer__ToLowerResponse(struct soap*, const char*, struct EchoServer__ToLowerResponse *, const char*);
SOAP_FMAC5 struct EchoServer__ToLowerResponse * SOAP_FMAC6 soap_new_EchoServer__ToLowerResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_EchoServer__ToLowerResponse(struct soap*, struct EchoServer__ToLowerResponse*);
SOAP_FMAC3 struct EchoServer__ToLowerResponse * SOAP_FMAC4 soap_instantiate_EchoServer__ToLowerResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_EchoServer__ToLowerResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_EchoServer__ToUpper
#define SOAP_TYPE_EchoServer__ToUpper (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_EchoServer__ToUpper(struct soap*, struct EchoServer__ToUpper *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_EchoServer__ToUpper(struct soap*, const struct EchoServer__ToUpper *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_EchoServer__ToUpper(struct soap*, const struct EchoServer__ToUpper *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_EchoServer__ToUpper(struct soap*, const char*, int, const struct EchoServer__ToUpper *, const char*);
SOAP_FMAC3 struct EchoServer__ToUpper * SOAP_FMAC4 soap_get_EchoServer__ToUpper(struct soap*, struct EchoServer__ToUpper *, const char*, const char*);
SOAP_FMAC3 struct EchoServer__ToUpper * SOAP_FMAC4 soap_in_EchoServer__ToUpper(struct soap*, const char*, struct EchoServer__ToUpper *, const char*);
SOAP_FMAC5 struct EchoServer__ToUpper * SOAP_FMAC6 soap_new_EchoServer__ToUpper(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_EchoServer__ToUpper(struct soap*, struct EchoServer__ToUpper*);
SOAP_FMAC3 struct EchoServer__ToUpper * SOAP_FMAC4 soap_instantiate_EchoServer__ToUpper(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_EchoServer__ToUpper(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_EchoServer__ToUpperResponse
#define SOAP_TYPE_EchoServer__ToUpperResponse (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_EchoServer__ToUpperResponse(struct soap*, struct EchoServer__ToUpperResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_EchoServer__ToUpperResponse(struct soap*, const struct EchoServer__ToUpperResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_EchoServer__ToUpperResponse(struct soap*, const struct EchoServer__ToUpperResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_EchoServer__ToUpperResponse(struct soap*, const char*, int, const struct EchoServer__ToUpperResponse *, const char*);
SOAP_FMAC3 struct EchoServer__ToUpperResponse * SOAP_FMAC4 soap_get_EchoServer__ToUpperResponse(struct soap*, struct EchoServer__ToUpperResponse *, const char*, const char*);
SOAP_FMAC3 struct EchoServer__ToUpperResponse * SOAP_FMAC4 soap_in_EchoServer__ToUpperResponse(struct soap*, const char*, struct EchoServer__ToUpperResponse *, const char*);
SOAP_FMAC5 struct EchoServer__ToUpperResponse * SOAP_FMAC6 soap_new_EchoServer__ToUpperResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_EchoServer__ToUpperResponse(struct soap*, struct EchoServer__ToUpperResponse*);
SOAP_FMAC3 struct EchoServer__ToUpperResponse * SOAP_FMAC4 soap_instantiate_EchoServer__ToUpperResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_EchoServer__ToUpperResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#endif

/* End of EchoServerH.h */
