/* gSoapMultiXTpmServer.cpp
   Generated by gSOAP 2.7.10 from gSoapMultiXTpmwsdl.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "gSoapMultiXTpmH.h"

SOAP_SOURCE_STAMP("@(#) gSoapMultiXTpmServer.cpp ver 2.7.10 2008-09-01 10:12:33 GMT")


SOAP_FMAC5 int SOAP_FMAC6 gSoapMultiXTpm_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif

	do
	{
#ifdef WITH_FASTCGI
		if (FCGI_Accept() < 0)
		{
			soap->error = SOAP_EOF;
			return soap_send_fault(soap);
		}
#endif

		soap_begin(soap);

#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif

		if (soap_begin_recv(soap))
		{	if (soap->error < SOAP_STOP)
			{
#ifdef WITH_FASTCGI
				soap_send_fault(soap);
#else 
				return soap_send_fault(soap);
#endif
			}
			soap_closesock(soap);

			continue;
		}

		if (soap_envelope_begin_in(soap)
		 || soap_recv_header(soap)
		 || soap_body_begin_in(soap)
		 || gSoapMultiXTpm_serve_request(soap)
		 || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 gSoapMultiXTpm_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:GetConfig"))
		return soap_serve___MultiXTpm11__GetConfig(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:UpdateConfig"))
		return soap_serve___MultiXTpm11__UpdateConfig(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:GetSystemStatus"))
		return soap_serve___MultiXTpm11__GetSystemStatus(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:RestartProcess"))
		return soap_serve___MultiXTpm11__RestartProcess(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:RestartGroup"))
		return soap_serve___MultiXTpm11__RestartGroup(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:StartProcess"))
		return soap_serve___MultiXTpm11__StartProcess(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:StartGroup"))
		return soap_serve___MultiXTpm11__StartGroup(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:ShutdownProcess"))
		return soap_serve___MultiXTpm11__ShutdownProcess(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:ShutdownGroup"))
		return soap_serve___MultiXTpm11__ShutdownGroup(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:SuspendGroup"))
		return soap_serve___MultiXTpm11__SuspendGroup(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:SuspendProcess"))
		return soap_serve___MultiXTpm11__SuspendProcess(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:ResumeGroup"))
		return soap_serve___MultiXTpm11__ResumeGroup(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:ResumeProcess"))
		return soap_serve___MultiXTpm11__ResumeProcess(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:RestartAll"))
		return soap_serve___MultiXTpm11__RestartAll(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:StartAll"))
		return soap_serve___MultiXTpm11__StartAll(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:ShutdownAll"))
		return soap_serve___MultiXTpm11__ShutdownAll(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:SuspendAll"))
		return soap_serve___MultiXTpm11__SuspendAll(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:ResumeAll"))
		return soap_serve___MultiXTpm11__ResumeAll(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:GetConfig"))
		return soap_serve___MultiXTpm12__GetConfig(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:UpdateConfig"))
		return soap_serve___MultiXTpm12__UpdateConfig(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:GetSystemStatus"))
		return soap_serve___MultiXTpm12__GetSystemStatus(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:RestartProcess"))
		return soap_serve___MultiXTpm12__RestartProcess(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:RestartGroup"))
		return soap_serve___MultiXTpm12__RestartGroup(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:StartProcess"))
		return soap_serve___MultiXTpm12__StartProcess(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:StartGroup"))
		return soap_serve___MultiXTpm12__StartGroup(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:ShutdownProcess"))
		return soap_serve___MultiXTpm12__ShutdownProcess(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:ShutdownGroup"))
		return soap_serve___MultiXTpm12__ShutdownGroup(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:SuspendGroup"))
		return soap_serve___MultiXTpm12__SuspendGroup(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:SuspendProcess"))
		return soap_serve___MultiXTpm12__SuspendProcess(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:ResumeGroup"))
		return soap_serve___MultiXTpm12__ResumeGroup(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:ResumeProcess"))
		return soap_serve___MultiXTpm12__ResumeProcess(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:RestartAll"))
		return soap_serve___MultiXTpm12__RestartAll(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:StartAll"))
		return soap_serve___MultiXTpm12__StartAll(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:ShutdownAll"))
		return soap_serve___MultiXTpm12__ShutdownAll(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:SuspendAll"))
		return soap_serve___MultiXTpm12__SuspendAll(soap);
	if (!soap_match_tag(soap, soap->tag, "MultiXTpm:ResumeAll"))
		return soap_serve___MultiXTpm12__ResumeAll(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm11__GetConfig(struct soap *soap)
{	struct __MultiXTpm11__GetConfig soap_tmp___MultiXTpm11__GetConfig;
	_MultiXTpm__GetConfigResponse MultiXTpm__GetConfigResponse;
	MultiXTpm__GetConfigResponse.soap_default(soap);
	soap_default___MultiXTpm11__GetConfig(soap, &soap_tmp___MultiXTpm11__GetConfig);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm11__GetConfig(soap, &soap_tmp___MultiXTpm11__GetConfig, "-MultiXTpm11:GetConfig", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm11__GetConfig(soap, soap_tmp___MultiXTpm11__GetConfig.MultiXTpm__GetConfig, &MultiXTpm__GetConfigResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__GetConfigResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__GetConfigResponse.soap_put(soap, "MultiXTpm:GetConfigResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__GetConfigResponse.soap_put(soap, "MultiXTpm:GetConfigResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm11__UpdateConfig(struct soap *soap)
{	struct __MultiXTpm11__UpdateConfig soap_tmp___MultiXTpm11__UpdateConfig;
	_MultiXTpm__UpdateConfigResponse MultiXTpm__UpdateConfigResponse;
	MultiXTpm__UpdateConfigResponse.soap_default(soap);
	soap_default___MultiXTpm11__UpdateConfig(soap, &soap_tmp___MultiXTpm11__UpdateConfig);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm11__UpdateConfig(soap, &soap_tmp___MultiXTpm11__UpdateConfig, "-MultiXTpm11:UpdateConfig", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm11__UpdateConfig(soap, soap_tmp___MultiXTpm11__UpdateConfig.MultiXTpm__UpdateConfig, &MultiXTpm__UpdateConfigResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__UpdateConfigResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__UpdateConfigResponse.soap_put(soap, "MultiXTpm:UpdateConfigResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__UpdateConfigResponse.soap_put(soap, "MultiXTpm:UpdateConfigResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm11__GetSystemStatus(struct soap *soap)
{	struct __MultiXTpm11__GetSystemStatus soap_tmp___MultiXTpm11__GetSystemStatus;
	_MultiXTpm__GetSystemStatusResponse MultiXTpm__GetSystemStatusResponse;
	MultiXTpm__GetSystemStatusResponse.soap_default(soap);
	soap_default___MultiXTpm11__GetSystemStatus(soap, &soap_tmp___MultiXTpm11__GetSystemStatus);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm11__GetSystemStatus(soap, &soap_tmp___MultiXTpm11__GetSystemStatus, "-MultiXTpm11:GetSystemStatus", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm11__GetSystemStatus(soap, soap_tmp___MultiXTpm11__GetSystemStatus.MultiXTpm__GetSystemStatus, &MultiXTpm__GetSystemStatusResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__GetSystemStatusResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__GetSystemStatusResponse.soap_put(soap, "MultiXTpm:GetSystemStatusResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__GetSystemStatusResponse.soap_put(soap, "MultiXTpm:GetSystemStatusResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm11__RestartProcess(struct soap *soap)
{	struct __MultiXTpm11__RestartProcess soap_tmp___MultiXTpm11__RestartProcess;
	_MultiXTpm__RestartProcessResponse MultiXTpm__RestartProcessResponse;
	MultiXTpm__RestartProcessResponse.soap_default(soap);
	soap_default___MultiXTpm11__RestartProcess(soap, &soap_tmp___MultiXTpm11__RestartProcess);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm11__RestartProcess(soap, &soap_tmp___MultiXTpm11__RestartProcess, "-MultiXTpm11:RestartProcess", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm11__RestartProcess(soap, soap_tmp___MultiXTpm11__RestartProcess.MultiXTpm__RestartProcess, &MultiXTpm__RestartProcessResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__RestartProcessResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__RestartProcessResponse.soap_put(soap, "MultiXTpm:RestartProcessResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__RestartProcessResponse.soap_put(soap, "MultiXTpm:RestartProcessResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm11__RestartGroup(struct soap *soap)
{	struct __MultiXTpm11__RestartGroup soap_tmp___MultiXTpm11__RestartGroup;
	_MultiXTpm__RestartGroupResponse MultiXTpm__RestartGroupResponse;
	MultiXTpm__RestartGroupResponse.soap_default(soap);
	soap_default___MultiXTpm11__RestartGroup(soap, &soap_tmp___MultiXTpm11__RestartGroup);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm11__RestartGroup(soap, &soap_tmp___MultiXTpm11__RestartGroup, "-MultiXTpm11:RestartGroup", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm11__RestartGroup(soap, soap_tmp___MultiXTpm11__RestartGroup.MultiXTpm__RestartGroup, &MultiXTpm__RestartGroupResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__RestartGroupResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__RestartGroupResponse.soap_put(soap, "MultiXTpm:RestartGroupResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__RestartGroupResponse.soap_put(soap, "MultiXTpm:RestartGroupResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm11__StartProcess(struct soap *soap)
{	struct __MultiXTpm11__StartProcess soap_tmp___MultiXTpm11__StartProcess;
	_MultiXTpm__StartProcessResponse MultiXTpm__StartProcessResponse;
	MultiXTpm__StartProcessResponse.soap_default(soap);
	soap_default___MultiXTpm11__StartProcess(soap, &soap_tmp___MultiXTpm11__StartProcess);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm11__StartProcess(soap, &soap_tmp___MultiXTpm11__StartProcess, "-MultiXTpm11:StartProcess", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm11__StartProcess(soap, soap_tmp___MultiXTpm11__StartProcess.MultiXTpm__StartProcess, &MultiXTpm__StartProcessResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__StartProcessResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__StartProcessResponse.soap_put(soap, "MultiXTpm:StartProcessResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__StartProcessResponse.soap_put(soap, "MultiXTpm:StartProcessResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm11__StartGroup(struct soap *soap)
{	struct __MultiXTpm11__StartGroup soap_tmp___MultiXTpm11__StartGroup;
	_MultiXTpm__StartGroupResponse MultiXTpm__StartGroupResponse;
	MultiXTpm__StartGroupResponse.soap_default(soap);
	soap_default___MultiXTpm11__StartGroup(soap, &soap_tmp___MultiXTpm11__StartGroup);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm11__StartGroup(soap, &soap_tmp___MultiXTpm11__StartGroup, "-MultiXTpm11:StartGroup", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm11__StartGroup(soap, soap_tmp___MultiXTpm11__StartGroup.MultiXTpm__StartGroup, &MultiXTpm__StartGroupResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__StartGroupResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__StartGroupResponse.soap_put(soap, "MultiXTpm:StartGroupResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__StartGroupResponse.soap_put(soap, "MultiXTpm:StartGroupResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm11__ShutdownProcess(struct soap *soap)
{	struct __MultiXTpm11__ShutdownProcess soap_tmp___MultiXTpm11__ShutdownProcess;
	_MultiXTpm__ShutdownProcessResponse MultiXTpm__ShutdownProcessResponse;
	MultiXTpm__ShutdownProcessResponse.soap_default(soap);
	soap_default___MultiXTpm11__ShutdownProcess(soap, &soap_tmp___MultiXTpm11__ShutdownProcess);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm11__ShutdownProcess(soap, &soap_tmp___MultiXTpm11__ShutdownProcess, "-MultiXTpm11:ShutdownProcess", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm11__ShutdownProcess(soap, soap_tmp___MultiXTpm11__ShutdownProcess.MultiXTpm__ShutdownProcess, &MultiXTpm__ShutdownProcessResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__ShutdownProcessResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__ShutdownProcessResponse.soap_put(soap, "MultiXTpm:ShutdownProcessResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__ShutdownProcessResponse.soap_put(soap, "MultiXTpm:ShutdownProcessResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm11__ShutdownGroup(struct soap *soap)
{	struct __MultiXTpm11__ShutdownGroup soap_tmp___MultiXTpm11__ShutdownGroup;
	_MultiXTpm__ShutdownGroupResponse MultiXTpm__ShutdownGroupResponse;
	MultiXTpm__ShutdownGroupResponse.soap_default(soap);
	soap_default___MultiXTpm11__ShutdownGroup(soap, &soap_tmp___MultiXTpm11__ShutdownGroup);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm11__ShutdownGroup(soap, &soap_tmp___MultiXTpm11__ShutdownGroup, "-MultiXTpm11:ShutdownGroup", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm11__ShutdownGroup(soap, soap_tmp___MultiXTpm11__ShutdownGroup.MultiXTpm__ShutdownGroup, &MultiXTpm__ShutdownGroupResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__ShutdownGroupResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__ShutdownGroupResponse.soap_put(soap, "MultiXTpm:ShutdownGroupResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__ShutdownGroupResponse.soap_put(soap, "MultiXTpm:ShutdownGroupResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm11__SuspendGroup(struct soap *soap)
{	struct __MultiXTpm11__SuspendGroup soap_tmp___MultiXTpm11__SuspendGroup;
	_MultiXTpm__SuspendGroupResponse MultiXTpm__SuspendGroupResponse;
	MultiXTpm__SuspendGroupResponse.soap_default(soap);
	soap_default___MultiXTpm11__SuspendGroup(soap, &soap_tmp___MultiXTpm11__SuspendGroup);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm11__SuspendGroup(soap, &soap_tmp___MultiXTpm11__SuspendGroup, "-MultiXTpm11:SuspendGroup", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm11__SuspendGroup(soap, soap_tmp___MultiXTpm11__SuspendGroup.MultiXTpm__SuspendGroup, &MultiXTpm__SuspendGroupResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__SuspendGroupResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__SuspendGroupResponse.soap_put(soap, "MultiXTpm:SuspendGroupResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__SuspendGroupResponse.soap_put(soap, "MultiXTpm:SuspendGroupResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm11__SuspendProcess(struct soap *soap)
{	struct __MultiXTpm11__SuspendProcess soap_tmp___MultiXTpm11__SuspendProcess;
	_MultiXTpm__SuspendProcessResponse MultiXTpm__SuspendProcessResponse;
	MultiXTpm__SuspendProcessResponse.soap_default(soap);
	soap_default___MultiXTpm11__SuspendProcess(soap, &soap_tmp___MultiXTpm11__SuspendProcess);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm11__SuspendProcess(soap, &soap_tmp___MultiXTpm11__SuspendProcess, "-MultiXTpm11:SuspendProcess", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm11__SuspendProcess(soap, soap_tmp___MultiXTpm11__SuspendProcess.MultiXTpm__SuspendProcess, &MultiXTpm__SuspendProcessResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__SuspendProcessResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__SuspendProcessResponse.soap_put(soap, "MultiXTpm:SuspendProcessResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__SuspendProcessResponse.soap_put(soap, "MultiXTpm:SuspendProcessResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm11__ResumeGroup(struct soap *soap)
{	struct __MultiXTpm11__ResumeGroup soap_tmp___MultiXTpm11__ResumeGroup;
	_MultiXTpm__ResumeGroupResponse MultiXTpm__ResumeGroupResponse;
	MultiXTpm__ResumeGroupResponse.soap_default(soap);
	soap_default___MultiXTpm11__ResumeGroup(soap, &soap_tmp___MultiXTpm11__ResumeGroup);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm11__ResumeGroup(soap, &soap_tmp___MultiXTpm11__ResumeGroup, "-MultiXTpm11:ResumeGroup", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm11__ResumeGroup(soap, soap_tmp___MultiXTpm11__ResumeGroup.MultiXTpm__ResumeGroup, &MultiXTpm__ResumeGroupResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__ResumeGroupResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__ResumeGroupResponse.soap_put(soap, "MultiXTpm:ResumeGroupResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__ResumeGroupResponse.soap_put(soap, "MultiXTpm:ResumeGroupResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm11__ResumeProcess(struct soap *soap)
{	struct __MultiXTpm11__ResumeProcess soap_tmp___MultiXTpm11__ResumeProcess;
	_MultiXTpm__ResumeProcessResponse MultiXTpm__ResumeProcessResponse;
	MultiXTpm__ResumeProcessResponse.soap_default(soap);
	soap_default___MultiXTpm11__ResumeProcess(soap, &soap_tmp___MultiXTpm11__ResumeProcess);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm11__ResumeProcess(soap, &soap_tmp___MultiXTpm11__ResumeProcess, "-MultiXTpm11:ResumeProcess", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm11__ResumeProcess(soap, soap_tmp___MultiXTpm11__ResumeProcess.MultiXTpm__ResumeProcess, &MultiXTpm__ResumeProcessResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__ResumeProcessResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__ResumeProcessResponse.soap_put(soap, "MultiXTpm:ResumeProcessResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__ResumeProcessResponse.soap_put(soap, "MultiXTpm:ResumeProcessResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm11__RestartAll(struct soap *soap)
{	struct __MultiXTpm11__RestartAll soap_tmp___MultiXTpm11__RestartAll;
	_MultiXTpm__RestartAllResponse MultiXTpm__RestartAllResponse;
	MultiXTpm__RestartAllResponse.soap_default(soap);
	soap_default___MultiXTpm11__RestartAll(soap, &soap_tmp___MultiXTpm11__RestartAll);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm11__RestartAll(soap, &soap_tmp___MultiXTpm11__RestartAll, "-MultiXTpm11:RestartAll", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm11__RestartAll(soap, soap_tmp___MultiXTpm11__RestartAll.MultiXTpm__RestartAll, &MultiXTpm__RestartAllResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__RestartAllResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__RestartAllResponse.soap_put(soap, "MultiXTpm:RestartAllResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__RestartAllResponse.soap_put(soap, "MultiXTpm:RestartAllResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm11__StartAll(struct soap *soap)
{	struct __MultiXTpm11__StartAll soap_tmp___MultiXTpm11__StartAll;
	_MultiXTpm__StartAllResponse MultiXTpm__StartAllResponse;
	MultiXTpm__StartAllResponse.soap_default(soap);
	soap_default___MultiXTpm11__StartAll(soap, &soap_tmp___MultiXTpm11__StartAll);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm11__StartAll(soap, &soap_tmp___MultiXTpm11__StartAll, "-MultiXTpm11:StartAll", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm11__StartAll(soap, soap_tmp___MultiXTpm11__StartAll.MultiXTpm__StartAll, &MultiXTpm__StartAllResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__StartAllResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__StartAllResponse.soap_put(soap, "MultiXTpm:StartAllResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__StartAllResponse.soap_put(soap, "MultiXTpm:StartAllResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm11__ShutdownAll(struct soap *soap)
{	struct __MultiXTpm11__ShutdownAll soap_tmp___MultiXTpm11__ShutdownAll;
	_MultiXTpm__ShutdownAllResponse MultiXTpm__ShutdownAllResponse;
	MultiXTpm__ShutdownAllResponse.soap_default(soap);
	soap_default___MultiXTpm11__ShutdownAll(soap, &soap_tmp___MultiXTpm11__ShutdownAll);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm11__ShutdownAll(soap, &soap_tmp___MultiXTpm11__ShutdownAll, "-MultiXTpm11:ShutdownAll", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm11__ShutdownAll(soap, soap_tmp___MultiXTpm11__ShutdownAll.MultiXTpm__ShutdownAll, &MultiXTpm__ShutdownAllResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__ShutdownAllResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__ShutdownAllResponse.soap_put(soap, "MultiXTpm:ShutdownAllResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__ShutdownAllResponse.soap_put(soap, "MultiXTpm:ShutdownAllResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm11__SuspendAll(struct soap *soap)
{	struct __MultiXTpm11__SuspendAll soap_tmp___MultiXTpm11__SuspendAll;
	_MultiXTpm__SuspendAllResponse MultiXTpm__SuspendAllResponse;
	MultiXTpm__SuspendAllResponse.soap_default(soap);
	soap_default___MultiXTpm11__SuspendAll(soap, &soap_tmp___MultiXTpm11__SuspendAll);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm11__SuspendAll(soap, &soap_tmp___MultiXTpm11__SuspendAll, "-MultiXTpm11:SuspendAll", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm11__SuspendAll(soap, soap_tmp___MultiXTpm11__SuspendAll.MultiXTpm__SuspendAll, &MultiXTpm__SuspendAllResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__SuspendAllResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__SuspendAllResponse.soap_put(soap, "MultiXTpm:SuspendAllResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__SuspendAllResponse.soap_put(soap, "MultiXTpm:SuspendAllResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm11__ResumeAll(struct soap *soap)
{	struct __MultiXTpm11__ResumeAll soap_tmp___MultiXTpm11__ResumeAll;
	_MultiXTpm__ResumeAllResponse MultiXTpm__ResumeAllResponse;
	MultiXTpm__ResumeAllResponse.soap_default(soap);
	soap_default___MultiXTpm11__ResumeAll(soap, &soap_tmp___MultiXTpm11__ResumeAll);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm11__ResumeAll(soap, &soap_tmp___MultiXTpm11__ResumeAll, "-MultiXTpm11:ResumeAll", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm11__ResumeAll(soap, soap_tmp___MultiXTpm11__ResumeAll.MultiXTpm__ResumeAll, &MultiXTpm__ResumeAllResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__ResumeAllResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__ResumeAllResponse.soap_put(soap, "MultiXTpm:ResumeAllResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__ResumeAllResponse.soap_put(soap, "MultiXTpm:ResumeAllResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm12__GetConfig(struct soap *soap)
{	struct __MultiXTpm12__GetConfig soap_tmp___MultiXTpm12__GetConfig;
	_MultiXTpm__GetConfigResponse MultiXTpm__GetConfigResponse;
	MultiXTpm__GetConfigResponse.soap_default(soap);
	soap_default___MultiXTpm12__GetConfig(soap, &soap_tmp___MultiXTpm12__GetConfig);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm12__GetConfig(soap, &soap_tmp___MultiXTpm12__GetConfig, "-MultiXTpm12:GetConfig", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm12__GetConfig(soap, soap_tmp___MultiXTpm12__GetConfig.MultiXTpm__GetConfig, &MultiXTpm__GetConfigResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__GetConfigResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__GetConfigResponse.soap_put(soap, "MultiXTpm:GetConfigResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__GetConfigResponse.soap_put(soap, "MultiXTpm:GetConfigResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm12__UpdateConfig(struct soap *soap)
{	struct __MultiXTpm12__UpdateConfig soap_tmp___MultiXTpm12__UpdateConfig;
	_MultiXTpm__UpdateConfigResponse MultiXTpm__UpdateConfigResponse;
	MultiXTpm__UpdateConfigResponse.soap_default(soap);
	soap_default___MultiXTpm12__UpdateConfig(soap, &soap_tmp___MultiXTpm12__UpdateConfig);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm12__UpdateConfig(soap, &soap_tmp___MultiXTpm12__UpdateConfig, "-MultiXTpm12:UpdateConfig", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm12__UpdateConfig(soap, soap_tmp___MultiXTpm12__UpdateConfig.MultiXTpm__UpdateConfig, &MultiXTpm__UpdateConfigResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__UpdateConfigResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__UpdateConfigResponse.soap_put(soap, "MultiXTpm:UpdateConfigResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__UpdateConfigResponse.soap_put(soap, "MultiXTpm:UpdateConfigResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm12__GetSystemStatus(struct soap *soap)
{	struct __MultiXTpm12__GetSystemStatus soap_tmp___MultiXTpm12__GetSystemStatus;
	_MultiXTpm__GetSystemStatusResponse MultiXTpm__GetSystemStatusResponse;
	MultiXTpm__GetSystemStatusResponse.soap_default(soap);
	soap_default___MultiXTpm12__GetSystemStatus(soap, &soap_tmp___MultiXTpm12__GetSystemStatus);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm12__GetSystemStatus(soap, &soap_tmp___MultiXTpm12__GetSystemStatus, "-MultiXTpm12:GetSystemStatus", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm12__GetSystemStatus(soap, soap_tmp___MultiXTpm12__GetSystemStatus.MultiXTpm__GetSystemStatus, &MultiXTpm__GetSystemStatusResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__GetSystemStatusResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__GetSystemStatusResponse.soap_put(soap, "MultiXTpm:GetSystemStatusResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__GetSystemStatusResponse.soap_put(soap, "MultiXTpm:GetSystemStatusResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm12__RestartProcess(struct soap *soap)
{	struct __MultiXTpm12__RestartProcess soap_tmp___MultiXTpm12__RestartProcess;
	_MultiXTpm__RestartProcessResponse MultiXTpm__RestartProcessResponse;
	MultiXTpm__RestartProcessResponse.soap_default(soap);
	soap_default___MultiXTpm12__RestartProcess(soap, &soap_tmp___MultiXTpm12__RestartProcess);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm12__RestartProcess(soap, &soap_tmp___MultiXTpm12__RestartProcess, "-MultiXTpm12:RestartProcess", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm12__RestartProcess(soap, soap_tmp___MultiXTpm12__RestartProcess.MultiXTpm__RestartProcess, &MultiXTpm__RestartProcessResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__RestartProcessResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__RestartProcessResponse.soap_put(soap, "MultiXTpm:RestartProcessResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__RestartProcessResponse.soap_put(soap, "MultiXTpm:RestartProcessResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm12__RestartGroup(struct soap *soap)
{	struct __MultiXTpm12__RestartGroup soap_tmp___MultiXTpm12__RestartGroup;
	_MultiXTpm__RestartGroupResponse MultiXTpm__RestartGroupResponse;
	MultiXTpm__RestartGroupResponse.soap_default(soap);
	soap_default___MultiXTpm12__RestartGroup(soap, &soap_tmp___MultiXTpm12__RestartGroup);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm12__RestartGroup(soap, &soap_tmp___MultiXTpm12__RestartGroup, "-MultiXTpm12:RestartGroup", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm12__RestartGroup(soap, soap_tmp___MultiXTpm12__RestartGroup.MultiXTpm__RestartGroup, &MultiXTpm__RestartGroupResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__RestartGroupResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__RestartGroupResponse.soap_put(soap, "MultiXTpm:RestartGroupResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__RestartGroupResponse.soap_put(soap, "MultiXTpm:RestartGroupResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm12__StartProcess(struct soap *soap)
{	struct __MultiXTpm12__StartProcess soap_tmp___MultiXTpm12__StartProcess;
	_MultiXTpm__StartProcessResponse MultiXTpm__StartProcessResponse;
	MultiXTpm__StartProcessResponse.soap_default(soap);
	soap_default___MultiXTpm12__StartProcess(soap, &soap_tmp___MultiXTpm12__StartProcess);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm12__StartProcess(soap, &soap_tmp___MultiXTpm12__StartProcess, "-MultiXTpm12:StartProcess", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm12__StartProcess(soap, soap_tmp___MultiXTpm12__StartProcess.MultiXTpm__StartProcess, &MultiXTpm__StartProcessResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__StartProcessResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__StartProcessResponse.soap_put(soap, "MultiXTpm:StartProcessResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__StartProcessResponse.soap_put(soap, "MultiXTpm:StartProcessResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm12__StartGroup(struct soap *soap)
{	struct __MultiXTpm12__StartGroup soap_tmp___MultiXTpm12__StartGroup;
	_MultiXTpm__StartGroupResponse MultiXTpm__StartGroupResponse;
	MultiXTpm__StartGroupResponse.soap_default(soap);
	soap_default___MultiXTpm12__StartGroup(soap, &soap_tmp___MultiXTpm12__StartGroup);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm12__StartGroup(soap, &soap_tmp___MultiXTpm12__StartGroup, "-MultiXTpm12:StartGroup", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm12__StartGroup(soap, soap_tmp___MultiXTpm12__StartGroup.MultiXTpm__StartGroup, &MultiXTpm__StartGroupResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__StartGroupResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__StartGroupResponse.soap_put(soap, "MultiXTpm:StartGroupResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__StartGroupResponse.soap_put(soap, "MultiXTpm:StartGroupResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm12__ShutdownProcess(struct soap *soap)
{	struct __MultiXTpm12__ShutdownProcess soap_tmp___MultiXTpm12__ShutdownProcess;
	_MultiXTpm__ShutdownProcessResponse MultiXTpm__ShutdownProcessResponse;
	MultiXTpm__ShutdownProcessResponse.soap_default(soap);
	soap_default___MultiXTpm12__ShutdownProcess(soap, &soap_tmp___MultiXTpm12__ShutdownProcess);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm12__ShutdownProcess(soap, &soap_tmp___MultiXTpm12__ShutdownProcess, "-MultiXTpm12:ShutdownProcess", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm12__ShutdownProcess(soap, soap_tmp___MultiXTpm12__ShutdownProcess.MultiXTpm__ShutdownProcess, &MultiXTpm__ShutdownProcessResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__ShutdownProcessResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__ShutdownProcessResponse.soap_put(soap, "MultiXTpm:ShutdownProcessResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__ShutdownProcessResponse.soap_put(soap, "MultiXTpm:ShutdownProcessResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm12__ShutdownGroup(struct soap *soap)
{	struct __MultiXTpm12__ShutdownGroup soap_tmp___MultiXTpm12__ShutdownGroup;
	_MultiXTpm__ShutdownGroupResponse MultiXTpm__ShutdownGroupResponse;
	MultiXTpm__ShutdownGroupResponse.soap_default(soap);
	soap_default___MultiXTpm12__ShutdownGroup(soap, &soap_tmp___MultiXTpm12__ShutdownGroup);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm12__ShutdownGroup(soap, &soap_tmp___MultiXTpm12__ShutdownGroup, "-MultiXTpm12:ShutdownGroup", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm12__ShutdownGroup(soap, soap_tmp___MultiXTpm12__ShutdownGroup.MultiXTpm__ShutdownGroup, &MultiXTpm__ShutdownGroupResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__ShutdownGroupResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__ShutdownGroupResponse.soap_put(soap, "MultiXTpm:ShutdownGroupResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__ShutdownGroupResponse.soap_put(soap, "MultiXTpm:ShutdownGroupResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm12__SuspendGroup(struct soap *soap)
{	struct __MultiXTpm12__SuspendGroup soap_tmp___MultiXTpm12__SuspendGroup;
	_MultiXTpm__SuspendGroupResponse MultiXTpm__SuspendGroupResponse;
	MultiXTpm__SuspendGroupResponse.soap_default(soap);
	soap_default___MultiXTpm12__SuspendGroup(soap, &soap_tmp___MultiXTpm12__SuspendGroup);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm12__SuspendGroup(soap, &soap_tmp___MultiXTpm12__SuspendGroup, "-MultiXTpm12:SuspendGroup", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm12__SuspendGroup(soap, soap_tmp___MultiXTpm12__SuspendGroup.MultiXTpm__SuspendGroup, &MultiXTpm__SuspendGroupResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__SuspendGroupResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__SuspendGroupResponse.soap_put(soap, "MultiXTpm:SuspendGroupResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__SuspendGroupResponse.soap_put(soap, "MultiXTpm:SuspendGroupResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm12__SuspendProcess(struct soap *soap)
{	struct __MultiXTpm12__SuspendProcess soap_tmp___MultiXTpm12__SuspendProcess;
	_MultiXTpm__SuspendProcessResponse MultiXTpm__SuspendProcessResponse;
	MultiXTpm__SuspendProcessResponse.soap_default(soap);
	soap_default___MultiXTpm12__SuspendProcess(soap, &soap_tmp___MultiXTpm12__SuspendProcess);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm12__SuspendProcess(soap, &soap_tmp___MultiXTpm12__SuspendProcess, "-MultiXTpm12:SuspendProcess", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm12__SuspendProcess(soap, soap_tmp___MultiXTpm12__SuspendProcess.MultiXTpm__SuspendProcess, &MultiXTpm__SuspendProcessResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__SuspendProcessResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__SuspendProcessResponse.soap_put(soap, "MultiXTpm:SuspendProcessResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__SuspendProcessResponse.soap_put(soap, "MultiXTpm:SuspendProcessResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm12__ResumeGroup(struct soap *soap)
{	struct __MultiXTpm12__ResumeGroup soap_tmp___MultiXTpm12__ResumeGroup;
	_MultiXTpm__ResumeGroupResponse MultiXTpm__ResumeGroupResponse;
	MultiXTpm__ResumeGroupResponse.soap_default(soap);
	soap_default___MultiXTpm12__ResumeGroup(soap, &soap_tmp___MultiXTpm12__ResumeGroup);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm12__ResumeGroup(soap, &soap_tmp___MultiXTpm12__ResumeGroup, "-MultiXTpm12:ResumeGroup", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm12__ResumeGroup(soap, soap_tmp___MultiXTpm12__ResumeGroup.MultiXTpm__ResumeGroup, &MultiXTpm__ResumeGroupResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__ResumeGroupResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__ResumeGroupResponse.soap_put(soap, "MultiXTpm:ResumeGroupResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__ResumeGroupResponse.soap_put(soap, "MultiXTpm:ResumeGroupResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm12__ResumeProcess(struct soap *soap)
{	struct __MultiXTpm12__ResumeProcess soap_tmp___MultiXTpm12__ResumeProcess;
	_MultiXTpm__ResumeProcessResponse MultiXTpm__ResumeProcessResponse;
	MultiXTpm__ResumeProcessResponse.soap_default(soap);
	soap_default___MultiXTpm12__ResumeProcess(soap, &soap_tmp___MultiXTpm12__ResumeProcess);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm12__ResumeProcess(soap, &soap_tmp___MultiXTpm12__ResumeProcess, "-MultiXTpm12:ResumeProcess", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm12__ResumeProcess(soap, soap_tmp___MultiXTpm12__ResumeProcess.MultiXTpm__ResumeProcess, &MultiXTpm__ResumeProcessResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__ResumeProcessResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__ResumeProcessResponse.soap_put(soap, "MultiXTpm:ResumeProcessResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__ResumeProcessResponse.soap_put(soap, "MultiXTpm:ResumeProcessResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm12__RestartAll(struct soap *soap)
{	struct __MultiXTpm12__RestartAll soap_tmp___MultiXTpm12__RestartAll;
	_MultiXTpm__RestartAllResponse MultiXTpm__RestartAllResponse;
	MultiXTpm__RestartAllResponse.soap_default(soap);
	soap_default___MultiXTpm12__RestartAll(soap, &soap_tmp___MultiXTpm12__RestartAll);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm12__RestartAll(soap, &soap_tmp___MultiXTpm12__RestartAll, "-MultiXTpm12:RestartAll", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm12__RestartAll(soap, soap_tmp___MultiXTpm12__RestartAll.MultiXTpm__RestartAll, &MultiXTpm__RestartAllResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__RestartAllResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__RestartAllResponse.soap_put(soap, "MultiXTpm:RestartAllResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__RestartAllResponse.soap_put(soap, "MultiXTpm:RestartAllResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm12__StartAll(struct soap *soap)
{	struct __MultiXTpm12__StartAll soap_tmp___MultiXTpm12__StartAll;
	_MultiXTpm__StartAllResponse MultiXTpm__StartAllResponse;
	MultiXTpm__StartAllResponse.soap_default(soap);
	soap_default___MultiXTpm12__StartAll(soap, &soap_tmp___MultiXTpm12__StartAll);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm12__StartAll(soap, &soap_tmp___MultiXTpm12__StartAll, "-MultiXTpm12:StartAll", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm12__StartAll(soap, soap_tmp___MultiXTpm12__StartAll.MultiXTpm__StartAll, &MultiXTpm__StartAllResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__StartAllResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__StartAllResponse.soap_put(soap, "MultiXTpm:StartAllResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__StartAllResponse.soap_put(soap, "MultiXTpm:StartAllResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm12__ShutdownAll(struct soap *soap)
{	struct __MultiXTpm12__ShutdownAll soap_tmp___MultiXTpm12__ShutdownAll;
	_MultiXTpm__ShutdownAllResponse MultiXTpm__ShutdownAllResponse;
	MultiXTpm__ShutdownAllResponse.soap_default(soap);
	soap_default___MultiXTpm12__ShutdownAll(soap, &soap_tmp___MultiXTpm12__ShutdownAll);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm12__ShutdownAll(soap, &soap_tmp___MultiXTpm12__ShutdownAll, "-MultiXTpm12:ShutdownAll", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm12__ShutdownAll(soap, soap_tmp___MultiXTpm12__ShutdownAll.MultiXTpm__ShutdownAll, &MultiXTpm__ShutdownAllResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__ShutdownAllResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__ShutdownAllResponse.soap_put(soap, "MultiXTpm:ShutdownAllResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__ShutdownAllResponse.soap_put(soap, "MultiXTpm:ShutdownAllResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm12__SuspendAll(struct soap *soap)
{	struct __MultiXTpm12__SuspendAll soap_tmp___MultiXTpm12__SuspendAll;
	_MultiXTpm__SuspendAllResponse MultiXTpm__SuspendAllResponse;
	MultiXTpm__SuspendAllResponse.soap_default(soap);
	soap_default___MultiXTpm12__SuspendAll(soap, &soap_tmp___MultiXTpm12__SuspendAll);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm12__SuspendAll(soap, &soap_tmp___MultiXTpm12__SuspendAll, "-MultiXTpm12:SuspendAll", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm12__SuspendAll(soap, soap_tmp___MultiXTpm12__SuspendAll.MultiXTpm__SuspendAll, &MultiXTpm__SuspendAllResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__SuspendAllResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__SuspendAllResponse.soap_put(soap, "MultiXTpm:SuspendAllResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__SuspendAllResponse.soap_put(soap, "MultiXTpm:SuspendAllResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___MultiXTpm12__ResumeAll(struct soap *soap)
{	struct __MultiXTpm12__ResumeAll soap_tmp___MultiXTpm12__ResumeAll;
	_MultiXTpm__ResumeAllResponse MultiXTpm__ResumeAllResponse;
	MultiXTpm__ResumeAllResponse.soap_default(soap);
	soap_default___MultiXTpm12__ResumeAll(soap, &soap_tmp___MultiXTpm12__ResumeAll);
	soap->encodingStyle = NULL;
	if (!soap_get___MultiXTpm12__ResumeAll(soap, &soap_tmp___MultiXTpm12__ResumeAll, "-MultiXTpm12:ResumeAll", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __MultiXTpm12__ResumeAll(soap, soap_tmp___MultiXTpm12__ResumeAll.MultiXTpm__ResumeAll, &MultiXTpm__ResumeAllResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	MultiXTpm__ResumeAllResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || MultiXTpm__ResumeAllResponse.soap_put(soap, "MultiXTpm:ResumeAllResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || MultiXTpm__ResumeAllResponse.soap_put(soap, "MultiXTpm:ResumeAllResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

/* End of gSoapMultiXTpmServer.cpp */
