/* CalculatorH.h
   Generated by gSOAP 2.7.10 from Calculator.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef CalculatorH_H
#define CalculatorH_H
#include "CalculatorStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_xsd__double
#define SOAP_TYPE_xsd__double (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__double(struct soap*, double *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__double(struct soap*, const double *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__double(struct soap*, const char*, int, const double *, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_get_xsd__double(struct soap*, double *, const char*, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_in_xsd__double(struct soap*, const char*, double *, const char*);

#ifndef SOAP_TYPE_double
#define SOAP_TYPE_double (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_double(struct soap*, double *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_double(struct soap*, const double *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_double(struct soap*, const char*, int, const double *, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_get_double(struct soap*, double *, const char*, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_in_double(struct soap*, const char*, double *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Fault * SOAP_FMAC6 soap_new_SOAP_ENV__Fault(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Reason * SOAP_FMAC6 soap_new_SOAP_ENV__Reason(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Detail * SOAP_FMAC6 soap_new_SOAP_ENV__Detail(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Code * SOAP_FMAC6 soap_new_SOAP_ENV__Code(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Header * SOAP_FMAC6 soap_new_SOAP_ENV__Header(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_Calculator__Div
#define SOAP_TYPE_Calculator__Div (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_Calculator__Div(struct soap*, struct Calculator__Div *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_Calculator__Div(struct soap*, const struct Calculator__Div *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_Calculator__Div(struct soap*, const struct Calculator__Div *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_Calculator__Div(struct soap*, const char*, int, const struct Calculator__Div *, const char*);
SOAP_FMAC3 struct Calculator__Div * SOAP_FMAC4 soap_get_Calculator__Div(struct soap*, struct Calculator__Div *, const char*, const char*);
SOAP_FMAC3 struct Calculator__Div * SOAP_FMAC4 soap_in_Calculator__Div(struct soap*, const char*, struct Calculator__Div *, const char*);
SOAP_FMAC5 struct Calculator__Div * SOAP_FMAC6 soap_new_Calculator__Div(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_Calculator__Div(struct soap*, struct Calculator__Div*);
SOAP_FMAC3 struct Calculator__Div * SOAP_FMAC4 soap_instantiate_Calculator__Div(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_Calculator__Div(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_Calculator__DivResponse
#define SOAP_TYPE_Calculator__DivResponse (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_Calculator__DivResponse(struct soap*, struct Calculator__DivResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_Calculator__DivResponse(struct soap*, const struct Calculator__DivResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_Calculator__DivResponse(struct soap*, const struct Calculator__DivResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_Calculator__DivResponse(struct soap*, const char*, int, const struct Calculator__DivResponse *, const char*);
SOAP_FMAC3 struct Calculator__DivResponse * SOAP_FMAC4 soap_get_Calculator__DivResponse(struct soap*, struct Calculator__DivResponse *, const char*, const char*);
SOAP_FMAC3 struct Calculator__DivResponse * SOAP_FMAC4 soap_in_Calculator__DivResponse(struct soap*, const char*, struct Calculator__DivResponse *, const char*);
SOAP_FMAC5 struct Calculator__DivResponse * SOAP_FMAC6 soap_new_Calculator__DivResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_Calculator__DivResponse(struct soap*, struct Calculator__DivResponse*);
SOAP_FMAC3 struct Calculator__DivResponse * SOAP_FMAC4 soap_instantiate_Calculator__DivResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_Calculator__DivResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_Calculator__Mul
#define SOAP_TYPE_Calculator__Mul (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_Calculator__Mul(struct soap*, struct Calculator__Mul *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_Calculator__Mul(struct soap*, const struct Calculator__Mul *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_Calculator__Mul(struct soap*, const struct Calculator__Mul *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_Calculator__Mul(struct soap*, const char*, int, const struct Calculator__Mul *, const char*);
SOAP_FMAC3 struct Calculator__Mul * SOAP_FMAC4 soap_get_Calculator__Mul(struct soap*, struct Calculator__Mul *, const char*, const char*);
SOAP_FMAC3 struct Calculator__Mul * SOAP_FMAC4 soap_in_Calculator__Mul(struct soap*, const char*, struct Calculator__Mul *, const char*);
SOAP_FMAC5 struct Calculator__Mul * SOAP_FMAC6 soap_new_Calculator__Mul(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_Calculator__Mul(struct soap*, struct Calculator__Mul*);
SOAP_FMAC3 struct Calculator__Mul * SOAP_FMAC4 soap_instantiate_Calculator__Mul(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_Calculator__Mul(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_Calculator__MulResponse
#define SOAP_TYPE_Calculator__MulResponse (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_Calculator__MulResponse(struct soap*, struct Calculator__MulResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_Calculator__MulResponse(struct soap*, const struct Calculator__MulResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_Calculator__MulResponse(struct soap*, const struct Calculator__MulResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_Calculator__MulResponse(struct soap*, const char*, int, const struct Calculator__MulResponse *, const char*);
SOAP_FMAC3 struct Calculator__MulResponse * SOAP_FMAC4 soap_get_Calculator__MulResponse(struct soap*, struct Calculator__MulResponse *, const char*, const char*);
SOAP_FMAC3 struct Calculator__MulResponse * SOAP_FMAC4 soap_in_Calculator__MulResponse(struct soap*, const char*, struct Calculator__MulResponse *, const char*);
SOAP_FMAC5 struct Calculator__MulResponse * SOAP_FMAC6 soap_new_Calculator__MulResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_Calculator__MulResponse(struct soap*, struct Calculator__MulResponse*);
SOAP_FMAC3 struct Calculator__MulResponse * SOAP_FMAC4 soap_instantiate_Calculator__MulResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_Calculator__MulResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_Calculator__Sub
#define SOAP_TYPE_Calculator__Sub (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_Calculator__Sub(struct soap*, struct Calculator__Sub *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_Calculator__Sub(struct soap*, const struct Calculator__Sub *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_Calculator__Sub(struct soap*, const struct Calculator__Sub *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_Calculator__Sub(struct soap*, const char*, int, const struct Calculator__Sub *, const char*);
SOAP_FMAC3 struct Calculator__Sub * SOAP_FMAC4 soap_get_Calculator__Sub(struct soap*, struct Calculator__Sub *, const char*, const char*);
SOAP_FMAC3 struct Calculator__Sub * SOAP_FMAC4 soap_in_Calculator__Sub(struct soap*, const char*, struct Calculator__Sub *, const char*);
SOAP_FMAC5 struct Calculator__Sub * SOAP_FMAC6 soap_new_Calculator__Sub(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_Calculator__Sub(struct soap*, struct Calculator__Sub*);
SOAP_FMAC3 struct Calculator__Sub * SOAP_FMAC4 soap_instantiate_Calculator__Sub(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_Calculator__Sub(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_Calculator__SubResponse
#define SOAP_TYPE_Calculator__SubResponse (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_Calculator__SubResponse(struct soap*, struct Calculator__SubResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_Calculator__SubResponse(struct soap*, const struct Calculator__SubResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_Calculator__SubResponse(struct soap*, const struct Calculator__SubResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_Calculator__SubResponse(struct soap*, const char*, int, const struct Calculator__SubResponse *, const char*);
SOAP_FMAC3 struct Calculator__SubResponse * SOAP_FMAC4 soap_get_Calculator__SubResponse(struct soap*, struct Calculator__SubResponse *, const char*, const char*);
SOAP_FMAC3 struct Calculator__SubResponse * SOAP_FMAC4 soap_in_Calculator__SubResponse(struct soap*, const char*, struct Calculator__SubResponse *, const char*);
SOAP_FMAC5 struct Calculator__SubResponse * SOAP_FMAC6 soap_new_Calculator__SubResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_Calculator__SubResponse(struct soap*, struct Calculator__SubResponse*);
SOAP_FMAC3 struct Calculator__SubResponse * SOAP_FMAC4 soap_instantiate_Calculator__SubResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_Calculator__SubResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_Calculator__Add
#define SOAP_TYPE_Calculator__Add (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_Calculator__Add(struct soap*, struct Calculator__Add *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_Calculator__Add(struct soap*, const struct Calculator__Add *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_Calculator__Add(struct soap*, const struct Calculator__Add *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_Calculator__Add(struct soap*, const char*, int, const struct Calculator__Add *, const char*);
SOAP_FMAC3 struct Calculator__Add * SOAP_FMAC4 soap_get_Calculator__Add(struct soap*, struct Calculator__Add *, const char*, const char*);
SOAP_FMAC3 struct Calculator__Add * SOAP_FMAC4 soap_in_Calculator__Add(struct soap*, const char*, struct Calculator__Add *, const char*);
SOAP_FMAC5 struct Calculator__Add * SOAP_FMAC6 soap_new_Calculator__Add(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_Calculator__Add(struct soap*, struct Calculator__Add*);
SOAP_FMAC3 struct Calculator__Add * SOAP_FMAC4 soap_instantiate_Calculator__Add(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_Calculator__Add(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_Calculator__AddResponse
#define SOAP_TYPE_Calculator__AddResponse (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_Calculator__AddResponse(struct soap*, struct Calculator__AddResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_Calculator__AddResponse(struct soap*, const struct Calculator__AddResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_Calculator__AddResponse(struct soap*, const struct Calculator__AddResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_Calculator__AddResponse(struct soap*, const char*, int, const struct Calculator__AddResponse *, const char*);
SOAP_FMAC3 struct Calculator__AddResponse * SOAP_FMAC4 soap_get_Calculator__AddResponse(struct soap*, struct Calculator__AddResponse *, const char*, const char*);
SOAP_FMAC3 struct Calculator__AddResponse * SOAP_FMAC4 soap_in_Calculator__AddResponse(struct soap*, const char*, struct Calculator__AddResponse *, const char*);
SOAP_FMAC5 struct Calculator__AddResponse * SOAP_FMAC6 soap_new_Calculator__AddResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_Calculator__AddResponse(struct soap*, struct Calculator__AddResponse*);
SOAP_FMAC3 struct Calculator__AddResponse * SOAP_FMAC4 soap_instantiate_Calculator__AddResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_Calculator__AddResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#endif

/* End of CalculatorH.h */
