/* soapH.h
   Generated by gSOAP 2.7.9l from dime.h
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (2)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_unsignedByte
#define SOAP_TYPE_unsignedByte (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedByte(struct soap*, unsigned char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedByte(struct soap*, const unsigned char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedByte(struct soap*, const char*, int, const unsigned char *, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_get_unsignedByte(struct soap*, unsigned char *, const char*, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_in_unsignedByte(struct soap*, const char*, unsigned char *, const char*);

#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedInt(struct soap*, unsigned int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedInt(struct soap*, const unsigned int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get_unsignedInt(struct soap*, unsigned int *, const char*, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in_unsignedInt(struct soap*, const char*, unsigned int *, const char*);

#ifndef SOAP_TYPE_arrayOfName
#define SOAP_TYPE_arrayOfName (26)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_arrayOfName(struct soap*, const char*, int, const arrayOfName *, const char*);
SOAP_FMAC3 arrayOfName * SOAP_FMAC4 soap_get_arrayOfName(struct soap*, arrayOfName *, const char*, const char*);
SOAP_FMAC3 arrayOfName * SOAP_FMAC4 soap_in_arrayOfName(struct soap*, const char*, arrayOfName *, const char*);
SOAP_FMAC5 arrayOfName * SOAP_FMAC6 soap_new_arrayOfName(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_arrayOfName(struct soap*, arrayOfName*);
SOAP_FMAC3 arrayOfName * SOAP_FMAC4 soap_instantiate_arrayOfName(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_arrayOfName(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_arrayOfData
#define SOAP_TYPE_arrayOfData (15)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_arrayOfData(struct soap*, const char*, int, const arrayOfData *, const char*);
SOAP_FMAC3 arrayOfData * SOAP_FMAC4 soap_get_arrayOfData(struct soap*, arrayOfData *, const char*, const char*);
SOAP_FMAC3 arrayOfData * SOAP_FMAC4 soap_in_arrayOfData(struct soap*, const char*, arrayOfData *, const char*);
SOAP_FMAC5 arrayOfData * SOAP_FMAC6 soap_new_arrayOfData(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_arrayOfData(struct soap*, arrayOfData*);
SOAP_FMAC3 arrayOfData * SOAP_FMAC4 soap_instantiate_arrayOfData(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_arrayOfData(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__Data
#define SOAP_TYPE_ns__Data (6)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__Data(struct soap*, const char*, int, const ns__Data *, const char*);
SOAP_FMAC3 ns__Data * SOAP_FMAC4 soap_get_ns__Data(struct soap*, ns__Data *, const char*, const char*);
SOAP_FMAC3 ns__Data * SOAP_FMAC4 soap_in_ns__Data(struct soap*, const char*, ns__Data *, const char*);
SOAP_FMAC5 ns__Data * SOAP_FMAC6 soap_new_ns__Data(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__Data(struct soap*, ns__Data*);
SOAP_FMAC3 ns__Data * SOAP_FMAC4 soap_instantiate_ns__Data(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__Data(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Fault * SOAP_FMAC6 soap_new_SOAP_ENV__Fault(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Reason * SOAP_FMAC6 soap_new_SOAP_ENV__Reason(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Detail * SOAP_FMAC6 soap_new_SOAP_ENV__Detail(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Code * SOAP_FMAC6 soap_new_SOAP_ENV__Code(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Header * SOAP_FMAC6 soap_new_SOAP_ENV__Header(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_ns__getImage
#define SOAP_TYPE_ns__getImage (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__getImage(struct soap*, struct ns__getImage *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__getImage(struct soap*, const struct ns__getImage *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__getImage(struct soap*, const struct ns__getImage *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__getImage(struct soap*, const char*, int, const struct ns__getImage *, const char*);
SOAP_FMAC3 struct ns__getImage * SOAP_FMAC4 soap_get_ns__getImage(struct soap*, struct ns__getImage *, const char*, const char*);
SOAP_FMAC3 struct ns__getImage * SOAP_FMAC4 soap_in_ns__getImage(struct soap*, const char*, struct ns__getImage *, const char*);
SOAP_FMAC5 struct ns__getImage * SOAP_FMAC6 soap_new_ns__getImage(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__getImage(struct soap*, struct ns__getImage*);
SOAP_FMAC3 struct ns__getImage * SOAP_FMAC4 soap_instantiate_ns__getImage(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__getImage(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__getImageResponse
#define SOAP_TYPE_ns__getImageResponse (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__getImageResponse(struct soap*, struct ns__getImageResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__getImageResponse(struct soap*, const struct ns__getImageResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__getImageResponse(struct soap*, const struct ns__getImageResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__getImageResponse(struct soap*, const char*, int, const struct ns__getImageResponse *, const char*);
SOAP_FMAC3 struct ns__getImageResponse * SOAP_FMAC4 soap_get_ns__getImageResponse(struct soap*, struct ns__getImageResponse *, const char*, const char*);
SOAP_FMAC3 struct ns__getImageResponse * SOAP_FMAC4 soap_in_ns__getImageResponse(struct soap*, const char*, struct ns__getImageResponse *, const char*);
SOAP_FMAC5 struct ns__getImageResponse * SOAP_FMAC6 soap_new_ns__getImageResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__getImageResponse(struct soap*, struct ns__getImageResponse*);
SOAP_FMAC3 struct ns__getImageResponse * SOAP_FMAC4 soap_instantiate_ns__getImageResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__getImageResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__getData
#define SOAP_TYPE_ns__getData (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__getData(struct soap*, struct ns__getData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__getData(struct soap*, const struct ns__getData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__getData(struct soap*, const struct ns__getData *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__getData(struct soap*, const char*, int, const struct ns__getData *, const char*);
SOAP_FMAC3 struct ns__getData * SOAP_FMAC4 soap_get_ns__getData(struct soap*, struct ns__getData *, const char*, const char*);
SOAP_FMAC3 struct ns__getData * SOAP_FMAC4 soap_in_ns__getData(struct soap*, const char*, struct ns__getData *, const char*);
SOAP_FMAC5 struct ns__getData * SOAP_FMAC6 soap_new_ns__getData(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__getData(struct soap*, struct ns__getData*);
SOAP_FMAC3 struct ns__getData * SOAP_FMAC4 soap_instantiate_ns__getData(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__getData(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__getDataResponse
#define SOAP_TYPE_ns__getDataResponse (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__getDataResponse(struct soap*, struct ns__getDataResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__getDataResponse(struct soap*, const struct ns__getDataResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__getDataResponse(struct soap*, const struct ns__getDataResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__getDataResponse(struct soap*, const char*, int, const struct ns__getDataResponse *, const char*);
SOAP_FMAC3 struct ns__getDataResponse * SOAP_FMAC4 soap_get_ns__getDataResponse(struct soap*, struct ns__getDataResponse *, const char*, const char*);
SOAP_FMAC3 struct ns__getDataResponse * SOAP_FMAC4 soap_in_ns__getDataResponse(struct soap*, const char*, struct ns__getDataResponse *, const char*);
SOAP_FMAC5 struct ns__getDataResponse * SOAP_FMAC6 soap_new_ns__getDataResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__getDataResponse(struct soap*, struct ns__getDataResponse*);
SOAP_FMAC3 struct ns__getDataResponse * SOAP_FMAC4 soap_instantiate_ns__getDataResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__getDataResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__putData
#define SOAP_TYPE_ns__putData (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__putData(struct soap*, struct ns__putData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__putData(struct soap*, const struct ns__putData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__putData(struct soap*, const struct ns__putData *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__putData(struct soap*, const char*, int, const struct ns__putData *, const char*);
SOAP_FMAC3 struct ns__putData * SOAP_FMAC4 soap_get_ns__putData(struct soap*, struct ns__putData *, const char*, const char*);
SOAP_FMAC3 struct ns__putData * SOAP_FMAC4 soap_in_ns__putData(struct soap*, const char*, struct ns__putData *, const char*);
SOAP_FMAC5 struct ns__putData * SOAP_FMAC6 soap_new_ns__putData(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__putData(struct soap*, struct ns__putData*);
SOAP_FMAC3 struct ns__putData * SOAP_FMAC4 soap_instantiate_ns__putData(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__putData(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__putDataResponse
#define SOAP_TYPE_ns__putDataResponse (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__putDataResponse(struct soap*, struct ns__putDataResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__putDataResponse(struct soap*, const struct ns__putDataResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__putDataResponse(struct soap*, const struct ns__putDataResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__putDataResponse(struct soap*, const char*, int, const struct ns__putDataResponse *, const char*);
SOAP_FMAC3 struct ns__putDataResponse * SOAP_FMAC4 soap_get_ns__putDataResponse(struct soap*, struct ns__putDataResponse *, const char*, const char*);
SOAP_FMAC3 struct ns__putDataResponse * SOAP_FMAC4 soap_in_ns__putDataResponse(struct soap*, const char*, struct ns__putDataResponse *, const char*);
SOAP_FMAC5 struct ns__putDataResponse * SOAP_FMAC6 soap_new_ns__putDataResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__putDataResponse(struct soap*, struct ns__putDataResponse*);
SOAP_FMAC3 struct ns__putDataResponse * SOAP_FMAC4 soap_instantiate_ns__putDataResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__putDataResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerToarrayOfName
#define SOAP_TYPE_PointerToarrayOfName (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToarrayOfName(struct soap*, arrayOfName *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToarrayOfName(struct soap*, arrayOfName *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToarrayOfName(struct soap*, const char *, int, arrayOfName *const*, const char *);
SOAP_FMAC3 arrayOfName ** SOAP_FMAC4 soap_get_PointerToarrayOfName(struct soap*, arrayOfName **, const char*, const char*);
SOAP_FMAC3 arrayOfName ** SOAP_FMAC4 soap_in_PointerToarrayOfName(struct soap*, const char*, arrayOfName **, const char*);

#ifndef SOAP_TYPE_PointerToarrayOfData
#define SOAP_TYPE_PointerToarrayOfData (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToarrayOfData(struct soap*, arrayOfData *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToarrayOfData(struct soap*, arrayOfData *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToarrayOfData(struct soap*, const char *, int, arrayOfData *const*, const char *);
SOAP_FMAC3 arrayOfData ** SOAP_FMAC4 soap_get_PointerToarrayOfData(struct soap*, arrayOfData **, const char*, const char*);
SOAP_FMAC3 arrayOfData ** SOAP_FMAC4 soap_in_PointerToarrayOfData(struct soap*, const char*, arrayOfData **, const char*);

#ifndef SOAP_TYPE_PointerTostring
#define SOAP_TYPE_PointerTostring (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostring(struct soap*, char **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostring(struct soap*, char **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostring(struct soap*, const char *, int, char **const*, const char *);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_get_PointerTostring(struct soap*, char ***, const char*, const char*);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_in_PointerTostring(struct soap*, const char*, char ***, const char*);

#ifndef SOAP_TYPE_PointerTons__Data
#define SOAP_TYPE_PointerTons__Data (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons__Data(struct soap*, ns__Data *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons__Data(struct soap*, ns__Data *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons__Data(struct soap*, const char *, int, ns__Data *const*, const char *);
SOAP_FMAC3 ns__Data ** SOAP_FMAC4 soap_get_PointerTons__Data(struct soap*, ns__Data **, const char*, const char*);
SOAP_FMAC3 ns__Data ** SOAP_FMAC4 soap_in_PointerTons__Data(struct soap*, const char*, ns__Data **, const char*);

#ifndef SOAP_TYPE_PointerTounsignedByte
#define SOAP_TYPE_PointerTounsignedByte (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTounsignedByte(struct soap*, unsigned char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTounsignedByte(struct soap*, unsigned char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTounsignedByte(struct soap*, const char *, int, unsigned char *const*, const char *);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_get_PointerTounsignedByte(struct soap*, unsigned char **, const char*, const char*);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_in_PointerTounsignedByte(struct soap*, const char*, unsigned char **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#endif

/* End of soapH.h */
