/* gSoapISO8583WSwsdl.h
   Generated by wsdl2h 1.2.10 from c:\Dev\MultiXTpmRelease\ISO8583Server\ISO8583WS.wsdl and ../gSoapTypeMap.dat
   2008-06-25 16:15:54 GMT
   Copyright (C) 2001-2008 Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/* NOTE:

 - Compile this file with soapcpp2 to complete the code generation process.
 - Use soapcpp2 option -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
 - Use wsdl2h options -c and -s to generate pure C code or C++ code without STL.
 - Use 'WS/typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) to browse this file.
 - Use wsdl2h option -l to view the software license terms.

   DO NOT include this file directly into your project.
   Include only the soapcpp2-generated headers and source code files.
*/

//gsoapopt w

/******************************************************************************\
 *                                                                            *
 * http://mitug.co.il/MultiXTpm/ISO8583WS                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


// STL vector containers (use option -s to disable)
#import "stlvector.h"

/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ISO8583WS = "http://mitug.co.il/MultiXTpm/ISO8583WS"

*/

//gsoap ISO8583WS schema namespace:	http://mitug.co.il/MultiXTpm/ISO8583WS
//gsoap ISO8583WS schema elementForm:	qualified
//gsoap ISO8583WS schema attributeForm:	unqualified

/******************************************************************************\
 *                                                                            *
 * Schema Types                                                               *
 *                                                                            *
\******************************************************************************/


/// Built-in type "xs:hexBinary".
class xsd__hexBinary { unsigned char *__ptr; int __size; };


//  Forward declaration of class ISO8583WS__ArrayOfCISO8583Msg.
class ISO8583WS__ArrayOfCISO8583Msg;

//  Forward declaration of class ISO8583WS__CISO8583Msg.
class ISO8583WS__CISO8583Msg;

//  Forward declaration of class ISO8583WS__ArrayOfAlNum.
class ISO8583WS__ArrayOfAlNum;

//  Forward declaration of class ISO8583WS__AlNum.
class ISO8583WS__AlNum;

//  Forward declaration of class ISO8583WS__ArrayOfNum.
class ISO8583WS__ArrayOfNum;

//  Forward declaration of class ISO8583WS__Num.
class ISO8583WS__Num;

//  Forward declaration of class ISO8583WS__ArrayOfBin.
class ISO8583WS__ArrayOfBin;

//  Forward declaration of class ISO8583WS__Bin.
class ISO8583WS__Bin;

//  Forward declaration of class ISO8583WS__ArrayOfISO8583Field.
class ISO8583WS__ArrayOfISO8583Field;

//  Forward declaration of class ISO8583WS__ISO8583Field.
class ISO8583WS__ISO8583Field;

//  Forward declaration of class _ISO8583WS__ISO8583Request.
class _ISO8583WS__ISO8583Request;

//  Forward declaration of class _ISO8583WS__ISO8583RequestResponse.
class _ISO8583WS__ISO8583RequestResponse;

/// "http://mitug.co.il/MultiXTpm/ISO8583WS":TValidationError is a simpleType restriction of xs:string.
/// Note: enum values are prefixed with 'ISO8583WS__TValidationError' to avoid name clashes, please use wsdl2h option -e to omit this prefix
enum ISO8583WS__TValidationError
{
	ISO8583WS__TValidationError__NoError,	///< xs:string value="NoError"
	ISO8583WS__TValidationError__InvalidMsgLength,	///< xs:string value="InvalidMsgLength"
	ISO8583WS__TValidationError__InvalidMsgFormat,	///< xs:string value="InvalidMsgFormat"
	ISO8583WS__TValidationError__InvalidMTIVersion,	///< xs:string value="InvalidMTIVersion"
	ISO8583WS__TValidationError__InvalidMTIClass,	///< xs:string value="InvalidMTIClass"
	ISO8583WS__TValidationError__InvalidMTIFunction,	///< xs:string value="InvalidMTIFunction"
	ISO8583WS__TValidationError__InvalidMTIOrigin,	///< xs:string value="InvalidMTIOrigin"
	ISO8583WS__TValidationError__InvalidElementID,	///< xs:string value="InvalidElementID"
	ISO8583WS__TValidationError__InvalidElementSize,	///< xs:string value="InvalidElementSize"
	ISO8583WS__TValidationError__InvalidElementValue,	///< xs:string value="InvalidElementValue"
	ISO8583WS__TValidationError__ElementIsMissing,	///< xs:string value="ElementIsMissing"
	ISO8583WS__TValidationError__ExtraElementsFound,	///< xs:string value="ExtraElementsFound"
	ISO8583WS__TValidationError__VersionNotSupported,	///< xs:string value="VersionNotSupported"
	ISO8583WS__TValidationError__MTINotSupported,	///< xs:string value="MTINotSupported"
	ISO8583WS__TValidationError__PANIsMissing,	///< xs:string value="PANIsMissing"
	ISO8583WS__TValidationError__ProcessingCodeIsMissing,	///< xs:string value="ProcessingCodeIsMissing"
	ISO8583WS__TValidationError__TransactionAmountIsMissing,	///< xs:string value="TransactionAmountIsMissing"
	ISO8583WS__TValidationError__TransactionCurrencyIsMissing,	///< xs:string value="TransactionCurrencyIsMissing"
	ISO8583WS__TValidationError__CardholderBillingAmountIsMissing,	///< xs:string value="CardholderBillingAmountIsMissing"
	ISO8583WS__TValidationError__CardholderBillingCurrencyIsNotEuro,	///< xs:string value="CardholderBillingCurrencyIsNotEuro"
	ISO8583WS__TValidationError__CardholderBillingConversionRateIsMissing,	///< xs:string value="CardholderBillingConversionRateIsMissing"
	ISO8583WS__TValidationError__CardholderBillingAmountWrong,	///< xs:string value="CardholderBillingAmountWrong"
	ISO8583WS__TValidationError__STANIsMissing,	///< xs:string value="STANIsMissing"
	ISO8583WS__TValidationError__DateTimeLocalIsMissing,	///< xs:string value="DateTimeLocalIsMissing"
	ISO8583WS__TValidationError__ExpirationDateIsMissing,	///< xs:string value="ExpirationDateIsMissing"
	ISO8583WS__TValidationError__POSDataCodeIsMissing,	///< xs:string value="POSDataCodeIsMissing"
	ISO8583WS__TValidationError__CardSequenceNumberIsMissing,	///< xs:string value="CardSequenceNumberIsMissing"
	ISO8583WS__TValidationError__FunctionCodeIsMissing,	///< xs:string value="FunctionCodeIsMissing"
	ISO8583WS__TValidationError__CardAcceptorBusinessCodeIsMissing,	///< xs:string value="CardAcceptorBusinessCodeIsMissing"
	ISO8583WS__TValidationError__AcquiringInstitutionIdentificationCodeIsMissing,	///< xs:string value="AcquiringInstitutionIdentificationCodeIsMissing"
	ISO8583WS__TValidationError__Track2DataIsMissing,	///< xs:string value="Track2DataIsMissing"
	ISO8583WS__TValidationError__RRNIsMissing,	///< xs:string value="RRNIsMissing"
	ISO8583WS__TValidationError__TerminalIDIsMissing,	///< xs:string value="TerminalIDIsMissing"
	ISO8583WS__TValidationError__CardAcceptorIdentificationCodeIsMissing,	///< xs:string value="CardAcceptorIdentificationCodeIsMissing"
	ISO8583WS__TValidationError__CardAcceptorNameLocationIsMissing,	///< xs:string value="CardAcceptorNameLocationIsMissing"
	ISO8583WS__TValidationError__PINIsMissing,	///< xs:string value="PINIsMissing"
	ISO8583WS__TValidationError__SecurityRelatedControlInformationIsMissing,	///< xs:string value="SecurityRelatedControlInformationIsMissing"
	ISO8583WS__TValidationError__AdditionalAmountsIsMissing,	///< xs:string value="AdditionalAmountsIsMissing"
	ISO8583WS__TValidationError__ICCDataIsMissing,	///< xs:string value="ICCDataIsMissing"
	ISO8583WS__TValidationError__AdditionalPrivateDataIsMissing,	///< xs:string value="AdditionalPrivateDataIsMissing"
	ISO8583WS__TValidationError__MAC1IsMissing,	///< xs:string value="MAC1IsMissing"
	ISO8583WS__TValidationError__FunctionCodeIsInvalid,	///< xs:string value="FunctionCodeIsInvalid"
	ISO8583WS__TValidationError__MessageReasonCodeIsMissing,	///< xs:string value="MessageReasonCodeIsMissing"
	ISO8583WS__TValidationError__TransactionDestinationInstitutionIdentificationCodeIsMissing,	///< xs:string value="TransactionDestinationInstitutionIdentificationCodeIsMissing"
	ISO8583WS__TValidationError__TransactionOriginatorInstitutionIdentificationCodeIsMissing,	///< xs:string value="TransactionOriginatorInstitutionIdentificationCodeIsMissing"
	ISO8583WS__TValidationError__MAC2IsMissing,	///< xs:string value="MAC2IsMissing"
	ISO8583WS__TValidationError__InvalidRequest,	///< xs:string value="InvalidRequest"
	ISO8583WS__TValidationError__OriginalAmountsIsMissing,	///< xs:string value="OriginalAmountsIsMissing"
	ISO8583WS__TValidationError__ApprovalCodeIsMissing,	///< xs:string value="ApprovalCodeIsMissing"
	ISO8583WS__TValidationError__OriginalDataElementsIsMissing,	///< xs:string value="OriginalDataElementsIsMissing"
	ISO8583WS__TValidationError__AuthorizingAgentInstitutionIdentificationCodeIsMissing,	///< xs:string value="AuthorizingAgentInstitutionIdentificationCodeIsMissing"
	ISO8583WS__TValidationError__ForwardToIssuerFailed,	///< xs:string value="ForwardToIssuerFailed"
	ISO8583WS__TValidationError__TerminalIDUnknown,	///< xs:string value="TerminalIDUnknown"
	ISO8583WS__TValidationError__InvalidProcessingCode,	///< xs:string value="InvalidProcessingCode"
	ISO8583WS__TValidationError__TransactionAmountAboveMaximum,	///< xs:string value="TransactionAmountAboveMaximum"
	ISO8583WS__TValidationError__GeneralSystemError,	///< xs:string value="GeneralSystemError"
	ISO8583WS__TValidationError__NoDatabaseConnection,	///< xs:string value="NoDatabaseConnection"
	ISO8583WS__TValidationError__RequestRejected,	///< xs:string value="RequestRejected"
};

/// "http://mitug.co.il/MultiXTpm/ISO8583WS":TValueType is a simpleType restriction of xs:string.
/// Note: enum values are prefixed with 'ISO8583WS__TValueType' to avoid name clashes, please use wsdl2h option -e to omit this prefix
enum ISO8583WS__TValueType
{
	ISO8583WS__TValueType__Numeric,	///< xs:string value="Numeric"
	ISO8583WS__TValueType__AlphaNumeric,	///< xs:string value="AlphaNumeric"
	ISO8583WS__TValueType__HexBinary,	///< xs:string value="HexBinary"
	ISO8583WS__TValueType__String,	///< xs:string value="String"
};

/// "http://mitug.co.il/MultiXTpm/ISO8583WS":ArrayOfCISO8583Msg is a complexType.
class ISO8583WS__ArrayOfCISO8583Msg
{ public:
/// Vector of ISO8583WS__CISO8583Msg* with length 0..unbounded
    std::vector<ISO8583WS__CISO8583Msg*> CISO8583Msg                    0;	///< Nullable pointer.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://mitug.co.il/MultiXTpm/ISO8583WS":CISO8583Msg is a complexType.
class ISO8583WS__CISO8583Msg
{ public:
/// Element MTI of type xs:int.
    int                                  MTI                            1;	///< Required element.
/// Element Error of type "http://mitug.co.il/MultiXTpm/ISO8583WS":TValidationError.
    enum ISO8583WS__TValidationError     Error                          1;	///< Required element.
/// Element AlphaNumericElements of type "http://mitug.co.il/MultiXTpm/ISO8583WS":ArrayOfAlNum.
    ISO8583WS__ArrayOfAlNum*             AlphaNumericElements           0;	///< Optional element.
/// Element NumericElements of type "http://mitug.co.il/MultiXTpm/ISO8583WS":ArrayOfNum.
    ISO8583WS__ArrayOfNum*               NumericElements                0;	///< Optional element.
/// Element BinaryElements of type "http://mitug.co.il/MultiXTpm/ISO8583WS":ArrayOfBin.
    ISO8583WS__ArrayOfBin*               BinaryElements                 0;	///< Optional element.
/// Element ISO8583Fields of type "http://mitug.co.il/MultiXTpm/ISO8583WS":ArrayOfISO8583Field.
    ISO8583WS__ArrayOfISO8583Field*      ISO8583Fields                  0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://mitug.co.il/MultiXTpm/ISO8583WS":ArrayOfAlNum is a complexType.
class ISO8583WS__ArrayOfAlNum
{ public:
/// Vector of ISO8583WS__AlNum* with length 0..unbounded
    std::vector<ISO8583WS__AlNum*      > AlNum                          0;	///< Nullable pointer.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://mitug.co.il/MultiXTpm/ISO8583WS":AlNum is a complexType.
class ISO8583WS__AlNum
{ public:
/// Element ID of type xs:int.
    int                                  ID                             1;	///< Required element.
/// Element Value of type xs:string.
    std::string*                         Value                          0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://mitug.co.il/MultiXTpm/ISO8583WS":ArrayOfNum is a complexType.
class ISO8583WS__ArrayOfNum
{ public:
/// Vector of ISO8583WS__Num* with length 0..unbounded
    std::vector<ISO8583WS__Num*        > Num                            0;	///< Nullable pointer.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://mitug.co.il/MultiXTpm/ISO8583WS":Num is a complexType.
class ISO8583WS__Num
{ public:
/// Element ID of type xs:int.
    int                                  ID                             1;	///< Required element.
/// Element Value of type xs:string.
    std::string*                         Value                          0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://mitug.co.il/MultiXTpm/ISO8583WS":ArrayOfBin is a complexType.
class ISO8583WS__ArrayOfBin
{ public:
/// Vector of ISO8583WS__Bin* with length 0..unbounded
    std::vector<ISO8583WS__Bin*        > Bin                            0;	///< Nullable pointer.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://mitug.co.il/MultiXTpm/ISO8583WS":Bin is a complexType.
class ISO8583WS__Bin
{ public:
/// Element ID of type xs:int.
    int                                  ID                             1;	///< Required element.
/// Element Value of type xs:hexBinary.
    xsd__hexBinary*                      Value                          0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://mitug.co.il/MultiXTpm/ISO8583WS":ArrayOfISO8583Field is a complexType.
class ISO8583WS__ArrayOfISO8583Field
{ public:
/// Vector of ISO8583WS__ISO8583Field* with length 0..unbounded
    std::vector<ISO8583WS__ISO8583Field*> Field                          0;	///< Nullable pointer.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://mitug.co.il/MultiXTpm/ISO8583WS":ISO8583Field is a complexType.
class ISO8583WS__ISO8583Field
{ public:
/// Attribute ID of type xs:int.
   @int                                  ID                             1;	///< Required attribute.
/// Attribute Value of type xs:string.
   @std::string*                         Value                          0;	///< Optional attribute.
/// Attribute ValueType of type "http://mitug.co.il/MultiXTpm/ISO8583WS":TValueType.
   @enum ISO8583WS__TValueType           ValueType                      0 = ISO8583WS__TValueType__String;	///< Default value="String".
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Element "http://mitug.co.il/MultiXTpm/ISO8583WS":ISO8583Request of complexType.

/// "http://mitug.co.il/MultiXTpm/ISO8583WS":ISO8583Request is a complexType.
class _ISO8583WS__ISO8583Request
{ public:
/// Element ISO8583Msgs of type "http://mitug.co.il/MultiXTpm/ISO8583WS":ArrayOfCISO8583Msg.
    ISO8583WS__ArrayOfCISO8583Msg*       ISO8583Msgs                    0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Element "http://mitug.co.il/MultiXTpm/ISO8583WS":ISO8583RequestResponse of complexType.

/// "http://mitug.co.il/MultiXTpm/ISO8583WS":ISO8583RequestResponse is a complexType.
class _ISO8583WS__ISO8583RequestResponse
{ public:
/// Element ISO8583RequestResult of type xs:boolean.
    bool                                 ISO8583RequestResult           1;	///< Required element.
/// Element ISO8583Msgs of type "http://mitug.co.il/MultiXTpm/ISO8583WS":ArrayOfCISO8583Msg.
    ISO8583WS__ArrayOfCISO8583Msg*       ISO8583Msgs                    0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ISO8583WS11 service name:	ISO8583WSSoap 
//gsoap ISO8583WS11 service type:	ISO8583WSSoap 
//gsoap ISO8583WS11 service port:	http://localhost:1651/ISO8583WS.asmx 
//gsoap ISO8583WS11 service namespace:	http://mitug.co.il/MultiXTpm/ISO8583WS/ISO8583WSSoap 
//gsoap ISO8583WS11 service transport:	http://schemas.xmlsoap.org/soap/http 

//gsoap ISO8583WS12 service name:	ISO8583WSSoap12 
//gsoap ISO8583WS12 service type:	ISO8583WSSoap 
//gsoap ISO8583WS12 service port:	http://localhost:1651/ISO8583WS.asmx 
//gsoap ISO8583WS12 service namespace:	http://mitug.co.il/MultiXTpm/ISO8583WS/ISO8583WSSoap12 
//gsoap ISO8583WS12 service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage Service Definitions

@section Service_bindings Bindings
  - @ref ISO8583WSSoap
  - @ref ISO8583WSSoap12

*/

/**

@page ISO8583WSSoap Binding "ISO8583WSSoap"

@section ISO8583WSSoap_operations Operations of Binding  "ISO8583WSSoap"
  - @ref __ISO8583WS11__ISO8583Request

@section ISO8583WSSoap_ports Endpoints of Binding  "ISO8583WSSoap"
  - http://localhost:1651/ISO8583WS.asmx

Note: use wsdl2h option -N to change the service binding prefix name

*/

/**

@page ISO8583WSSoap12 Binding "ISO8583WSSoap12"

@section ISO8583WSSoap12_operations Operations of Binding  "ISO8583WSSoap12"
  - @ref __ISO8583WS12__ISO8583Request

@section ISO8583WSSoap12_ports Endpoints of Binding  "ISO8583WSSoap12"
  - http://localhost:1651/ISO8583WS.asmx

Note: use wsdl2h option -N to change the service binding prefix name

*/

/******************************************************************************\
 *                                                                            *
 * ISO8583WSSoap                                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * __ISO8583WS11__ISO8583Request                                              *
 *                                                                            *
\******************************************************************************/


/// Operation "__ISO8583WS11__ISO8583Request" of service binding "ISO8583WSSoap"

/**

Operation details:

  - SOAP document/literal style
  - SOAP action="http://mitug.co.il/MultiXTpm/ISO8583WS/ISO8583Request"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ISO8583WS11__ISO8583Request(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _ISO8583WS__ISO8583Request*         ISO8583WS__ISO8583Request,
    // response parameters:
    _ISO8583WS__ISO8583RequestResponse* ISO8583WS__ISO8583RequestResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ISO8583WS11__ISO8583Request(
    struct soap *soap,
    // request parameters:
    _ISO8583WS__ISO8583Request*         ISO8583WS__ISO8583Request,
    // response parameters:
    _ISO8583WS__ISO8583RequestResponse* ISO8583WS__ISO8583RequestResponse
  );
@endcode

C++ proxy class (defined in soapISO8583WSSoapProxy.h):
  class ISO8583WSSoap;

Note: use soapcpp2 option '-i' to generate improved proxy and service classes;

*/

//gsoap ISO8583WS11 service method-style:	ISO8583Request document
//gsoap ISO8583WS11 service method-encoding:	ISO8583Request literal
//gsoap ISO8583WS11 service method-action:	ISO8583Request http://mitug.co.il/MultiXTpm/ISO8583WS/ISO8583Request
int __ISO8583WS11__ISO8583Request(
    _ISO8583WS__ISO8583Request*         ISO8583WS__ISO8583Request,	///< Request parameter
    _ISO8583WS__ISO8583RequestResponse* ISO8583WS__ISO8583RequestResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * ISO8583WSSoap12                                                            *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * __ISO8583WS12__ISO8583Request                                              *
 *                                                                            *
\******************************************************************************/


/// Operation "__ISO8583WS12__ISO8583Request" of service binding "ISO8583WSSoap12"

/**

Operation details:

  - SOAP document/literal style
  - SOAP action="http://mitug.co.il/MultiXTpm/ISO8583WS/ISO8583Request"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ISO8583WS12__ISO8583Request(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _ISO8583WS__ISO8583Request*         ISO8583WS__ISO8583Request,
    // response parameters:
    _ISO8583WS__ISO8583RequestResponse* ISO8583WS__ISO8583RequestResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ISO8583WS12__ISO8583Request(
    struct soap *soap,
    // request parameters:
    _ISO8583WS__ISO8583Request*         ISO8583WS__ISO8583Request,
    // response parameters:
    _ISO8583WS__ISO8583RequestResponse* ISO8583WS__ISO8583RequestResponse
  );
@endcode

C++ proxy class (defined in soapISO8583WSSoap12Proxy.h):
  class ISO8583WSSoap12;

Note: use soapcpp2 option '-i' to generate improved proxy and service classes;

*/

//gsoap ISO8583WS12 service method-style:	ISO8583Request document
//gsoap ISO8583WS12 service method-encoding:	ISO8583Request literal
//gsoap ISO8583WS12 service method-action:	ISO8583Request http://mitug.co.il/MultiXTpm/ISO8583WS/ISO8583Request
int __ISO8583WS12__ISO8583Request(
    _ISO8583WS__ISO8583Request*         ISO8583WS__ISO8583Request,	///< Request parameter
    _ISO8583WS__ISO8583RequestResponse* ISO8583WS__ISO8583RequestResponse	///< Response parameter
);

/* End of gSoapISO8583WSwsdl.h */
