/* gSoapISO8583WSServer.cpp
   Generated by gSOAP 2.7.10 from gSoapISO8583WSwsdl.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "gSoapISO8583WSH.h"

SOAP_SOURCE_STAMP("@(#) gSoapISO8583WSServer.cpp ver 2.7.10 2008-06-25 16:15:54 GMT")


SOAP_FMAC5 int SOAP_FMAC6 gSoapISO8583WS_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif

	do
	{
#ifdef WITH_FASTCGI
		if (FCGI_Accept() < 0)
		{
			soap->error = SOAP_EOF;
			return soap_send_fault(soap);
		}
#endif

		soap_begin(soap);

#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif

		if (soap_begin_recv(soap))
		{	if (soap->error < SOAP_STOP)
			{
#ifdef WITH_FASTCGI
				soap_send_fault(soap);
#else 
				return soap_send_fault(soap);
#endif
			}
			soap_closesock(soap);

			continue;
		}

		if (soap_envelope_begin_in(soap)
		 || soap_recv_header(soap)
		 || soap_body_begin_in(soap)
		 || gSoapISO8583WS_serve_request(soap)
		 || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 gSoapISO8583WS_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ISO8583WS:ISO8583Request"))
		return soap_serve___ISO8583WS11__ISO8583Request(soap);
	if (!soap_match_tag(soap, soap->tag, "ISO8583WS:ISO8583Request"))
		return soap_serve___ISO8583WS12__ISO8583Request(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ISO8583WS11__ISO8583Request(struct soap *soap)
{	struct __ISO8583WS11__ISO8583Request soap_tmp___ISO8583WS11__ISO8583Request;
	_ISO8583WS__ISO8583RequestResponse ISO8583WS__ISO8583RequestResponse;
	ISO8583WS__ISO8583RequestResponse.soap_default(soap);
	soap_default___ISO8583WS11__ISO8583Request(soap, &soap_tmp___ISO8583WS11__ISO8583Request);
	soap->encodingStyle = NULL;
	if (!soap_get___ISO8583WS11__ISO8583Request(soap, &soap_tmp___ISO8583WS11__ISO8583Request, "-ISO8583WS11:ISO8583Request", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ISO8583WS11__ISO8583Request(soap, soap_tmp___ISO8583WS11__ISO8583Request.ISO8583WS__ISO8583Request, &ISO8583WS__ISO8583RequestResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ISO8583WS__ISO8583RequestResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ISO8583WS__ISO8583RequestResponse.soap_put(soap, "ISO8583WS:ISO8583RequestResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ISO8583WS__ISO8583RequestResponse.soap_put(soap, "ISO8583WS:ISO8583RequestResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ISO8583WS12__ISO8583Request(struct soap *soap)
{	struct __ISO8583WS12__ISO8583Request soap_tmp___ISO8583WS12__ISO8583Request;
	_ISO8583WS__ISO8583RequestResponse ISO8583WS__ISO8583RequestResponse;
	ISO8583WS__ISO8583RequestResponse.soap_default(soap);
	soap_default___ISO8583WS12__ISO8583Request(soap, &soap_tmp___ISO8583WS12__ISO8583Request);
	soap->encodingStyle = NULL;
	if (!soap_get___ISO8583WS12__ISO8583Request(soap, &soap_tmp___ISO8583WS12__ISO8583Request, "-ISO8583WS12:ISO8583Request", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ISO8583WS12__ISO8583Request(soap, soap_tmp___ISO8583WS12__ISO8583Request.ISO8583WS__ISO8583Request, &ISO8583WS__ISO8583RequestResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ISO8583WS__ISO8583RequestResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ISO8583WS__ISO8583RequestResponse.soap_put(soap, "ISO8583WS:ISO8583RequestResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ISO8583WS__ISO8583RequestResponse.soap_put(soap, "ISO8583WS:ISO8583RequestResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

/* End of gSoapISO8583WSServer.cpp */
